import { Achievement } from './types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-001',
    title: 'National Cybersecurity CTF Championship',
    type: 'CTF',
    result: '1st Place',
    students: ['Ananya Sharma', 'Rohan Patel', 'Priya Desai'],
    date: 'January 2025',
    description: 'Secured first place in the national-level Capture The Flag competition, solving 45+ challenges across web exploitation, reverse engineering, cryptography, and forensics categories.',
    images: [
      'https://picsum.photos/seed/ctf-trophy/800/600',
      'https://picsum.photos/seed/ctf-team/800/600',
      'https://picsum.photos/seed/ctf-setup/800/600',
    ],
  },
  {
    id: 'ach-002',
    title: 'Smart India Hackathon - Security Module',
    type: 'Hackathon',
    result: '2nd Place',
    students: ['Vikram Singh', 'Neha Reddy', 'Arjun Kumar', 'Sneha Gupta'],
    date: 'August 2024',
    description: 'Developed an AI-powered threat detection system for IoT devices using machine learning to identify anomalous network behavior and prevent zero-day attacks.',
    images: [
      'https://picsum.photos/seed/sih-project/800/600',
      'https://picsum.photos/seed/sih-demo/800/600',
    ],
  },
  {
    id: 'ach-003',
    title: 'CodeFest National Programming Marathon',
    type: 'Coding',
    result: '1st Place',
    students: ['Aditya Verma', 'Kavya Nair'],
    date: 'November 2024',
    description: 'Won the 24-hour coding marathon by developing a secure file-sharing platform with end-to-end encryption and blockchain-based access control.',
    images: [
      'https://picsum.photos/seed/codefest-win/800/600',
    ],
  },
  {
    id: 'ach-004',
    title: 'National Bug Bounty Championship',
    type: 'CTF',
    result: '3rd Place',
    students: ['Rahul Mehta', 'Ishita Joshi', 'Karan Malhotra'],
    date: 'September 2024',
    description: 'Identified and reported 12 critical vulnerabilities in live web applications during the 48-hour competition. Found SQL injection, authentication bypass, and privilege escalation issues.',
    images: [
      'https://picsum.photos/seed/bugbounty-cert/800/600',
      'https://picsum.photos/seed/bugbounty-team/800/600',
    ],
  },
  {
    id: 'ach-005',
    title: 'Best Research Paper Award',
    type: 'Other',
    result: 'Winner',
    students: ['Divya Saxena', 'Amit Rao'],
    date: 'June 2024',
    description: 'Awarded for research on "Novel Approaches to Ransomware Detection Using Behavioral Analysis and Graph Neural Networks" achieving 97% detection accuracy.',
    images: [
      'https://picsum.photos/seed/research-award/800/600',
    ],
  },
  {
    id: 'ach-006',
    title: 'DevFest Cloud Security Challenge',
    type: 'Hackathon',
    result: '1st Place',
    students: ['Sanjay Gupta', 'Meera Iyer', 'Tanvi Shah'],
    date: 'December 2024',
    description: 'Built a cloud-native security monitoring platform that detects misconfigurations and compliance violations in AWS, Azure, and GCP environments.',
    images: [
      'https://picsum.photos/seed/devfest-stage/800/600',
      'https://picsum.photos/seed/devfest-project/800/600',
      'https://picsum.photos/seed/devfest-trophy/800/600',
    ],
  },
  {
    id: 'ach-007',
    title: 'LeetCode Weekly Contest Champion',
    type: 'Coding',
    result: 'Top 10',
    students: ['Rajesh Kumar'],
    date: 'October 2024',
    description: 'Ranked in the top 10 globally in LeetCode\'s annual championship, solving complex algorithmic challenges in data structures and dynamic programming.',
    images: [
      'https://picsum.photos/seed/leetcode-badge/800/600',
    ],
  },
  {
    id: 'ach-008',
    title: 'Defensive Security Competition',
    type: 'CTF',
    result: '2nd Place',
    students: ['Lakshmi Nair', 'Varun Reddy', 'Pooja Singh', 'Harsh Agarwal'],
    date: 'July 2024',
    description: 'Defended enterprise infrastructure against simulated APTs in a 36-hour red vs blue team competition. Successfully mitigated ransomware and DDoS attacks.',
    images: [
      'https://picsum.photos/seed/defsec-ops/800/600',
      'https://picsum.photos/seed/defsec-award/800/600',
    ],
  },
  {
    id: 'ach-009',
    title: 'Microsoft Imagine Cup - Security Track',
    type: 'Hackathon',
    result: 'Finalist',
    students: ['Aarav Patel', 'Diya Kapoor', 'Mohit Sharma'],
    date: 'March 2024',
    description: 'Created an AI-based phishing detection browser extension that analyzes website authenticity and behavioral patterns with 95% accuracy.',
    images: [
      'https://picsum.photos/seed/imaginecup-pitch/800/600',
      'https://picsum.photos/seed/imaginecup-demo/800/600',
    ],
  },
  {
    id: 'ach-010',
    title: 'Codeforces Division 1 Promotion',
    type: 'Coding',
    result: 'Candidate Master',
    students: ['Nisha Verma', 'Aryan Jain'],
    date: 'May 2024',
    description: 'Achieved Candidate Master rating on Codeforces through consistent performance in competitive programming contests.',
    images: [
      'https://picsum.photos/seed/codeforces-rating/800/600',
    ],
  },
  {
    id: 'ach-011',
    title: 'ROOTCON Hacking Conference CTF',
    type: 'CTF',
    result: '1st Place',
    students: ['Siddharth Bose', 'Riya Chatterjee'],
    date: 'April 2024',
    description: 'Dominated the international CTF competition, specializing in binary exploitation and reverse engineering. Discovered a novel ROP chain technique.',
    images: [
      'https://picsum.photos/seed/rootcon-victory/800/600',
      'https://picsum.photos/seed/rootcon-conf/800/600',
      'https://picsum.photos/seed/rootcon-cert/800/600',
    ],
  },
  {
    id: 'ach-012',
    title: 'ETHIndia Blockchain Hackathon',
    type: 'Hackathon',
    result: 'Winner',
    students: ['Karthik Menon', 'Shreya Das', 'Nikhil Rao', 'Anjali Mishra'],
    date: 'December 2023',
    description: 'Developed a decentralized identity verification system using zero-knowledge proofs and blockchain technology for privacy-preserving authentication.',
    images: [
      'https://picsum.photos/seed/ethindia-winner/800/600',
    ],
  },
  {
    id: 'ach-013',
    title: 'Patent Grant for AI Security Algorithm',
    type: 'Other',
    result: 'Patent Granted',
    students: ['Manish Kumar', 'Swati Bhatt'],
    date: 'February 2024',
    description: 'Received patent for a novel ML algorithm that detects polymorphic malware by analyzing execution patterns and memory footprints.',
    images: [
      'https://picsum.photos/seed/patent-doc/800/600',
    ],
  },
  {
    id: 'ach-014',
    title: 'ACM ICPC Regional Competition',
    type: 'Coding',
    result: '5th Place',
    students: ['Gaurav Tripathi', 'Aditi Kulkarni', 'Vishal Pandey'],
    date: 'January 2024',
    description: 'Competed in the ACM International Collegiate Programming Contest regional round, solving 8 out of 12 advanced algorithmic problems.',
    images: [
      'https://picsum.photos/seed/icpc-team/800/600',
      'https://picsum.photos/seed/icpc-venue/800/600',
    ],
  },
];
